### ISSUE TITLE
Counting of erlang opcode calls

### ISSUE THREAD

**Issue by octavonce** [purpleprotocol/purple#2]
In order to be able to halt contract execution we need to be able to count the number of erlang opcodes that have been called by a script at runtime.

Now, this is tricky since erlang does not provide an API for doing such a thing. 

We should try to use erlang's opcodes but if this isn't possible we should discuss about writing a vm layer.

**Comment by hpaul** [comment]
After a contract was successfully compiled and passed blacklist&whitelist checks should be send to `ContractWorker`process. Here contract it's executed and checked constantly for it's reduction counts (this measure the steps of each function and cont how many time was called).
